name: checks

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: "3.12"

      - name: Install dependencies from the lockfile
        run: uv sync --frozen --all-groups

      - name: ruff
        run: uv run ruff check .

      - name: mypy
        run: uv run mypy

      - name: pytest
        run: uv run pytest